---
title: "Homework 5"
author: "Zhezheng Jin"
output:
  pdf_document:
    latex_engine: xelatex
    toc: yes
    toc_depth: 2
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '2'
header-includes:
- \usepackage{fancyhdr}
- \usepackage{lipsum}
- \pagestyle{fancy}
- \fancyhead[R]{\thepage}
- \fancypagestyle{plain}{\pagestyle{fancy}}
editor_options: 
  chunk_output_type: console
--- 

\newpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
```

```{r, echo = TRUE, message = FALSE, results='hide', warning=FALSE}
library(tidyverse)
library(caret)
library(mlbench)
library(pROC)
library(pdp)
library(ISLR)
library(caret)
library(rpart)
library(rpart.plot)
library(ranger)
library(tidymodels)
```

## 1.Auto Data
```{r}
# Data Import
auto <- read_csv("auto.csv") %>%
  mutate(
    mpg_cat = as.factor(mpg_cat),
    origin = factor(origin, levels = 1:3),
    cylinders = as.factor(cylinders)) 

skimr::skim(auto)
contrasts(auto$mpg_cat)
# data partition
set.seed(2358)
data_split2 <- initial_split(auto, prop = 0.7)
train2 <- training(data_split2)
test2 <- testing(data_split2)
```







